/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.view.interfaces.IAllEntriesView;
import javax.swing.ListSelectionModel;

/**
 *
 * @author ALEX
 */
public class AllEntriesFrame extends AbstractEntriesFrame implements IAllEntriesView {

    /**
     * Creates new form EntriesFrame
     */
    public AllEntriesFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setChildCloseOperation();
        tableModel.hideColumn(0);
        jtblEntries.getColumnModel().getColumn(0).setCellRenderer(getCenterCellRender());
        jtblEntries.getColumnModel().getColumn(1).setCellRenderer(getCenterCellRender());
        jtblEntries.getColumnModel().getColumn(7).setCellRenderer(getCenterCellRender());
        jtblEntries.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jscrollEntries = new javax.swing.JScrollPane();
        jtblEntries = new javax.swing.JTable();
        jbtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Таблица записей на прием к врачу");
        setResizable(false);

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText("Все записи пациентов");

        jtblEntries.setModel(tableModel);
        jtblEntries.setFillsViewportHeight(true);
        jtblEntries.setName(""); // NOI18N
        jtblEntries.setRowHeight(20);
        jscrollEntries.setViewportView(jtblEntries);

        jbtnClose.setText("<< Вернуться к выбору даты");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscrollEntries, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnClose)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrollEntries, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        presenter.showCalendar();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnClose;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JScrollPane jscrollEntries;
    private javax.swing.JTable jtblEntries;
    // End of variables declaration//GEN-END:variables
}
