/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.exceptions.WrongDayOfWeekException;
import com.view.interfaces.ICalendarView;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author ALEX
 */
public class CalendarFrame extends AbstractFrame implements ICalendarView {

    @Override
    public Date getCheckedDate() throws WrongDayOfWeekException {
        Date date = jCalendar.getDate();
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(date);
        int dayOfWeek = calendar.get(Calendar.DAY_OF_WEEK);

        switch (dayOfWeek) {
            case Calendar.SUNDAY:
                throw new WrongDayOfWeekException();
            default:
                return date;
        }
    }

    @Override
    public void lockEntriesView() {
        jbtnShowDateEntries.setEnabled(false);
        jbtnShowAllEntries.setEnabled(false);
    }

    @Override
    public void unlockEntriesView() {
        jbtnShowDateEntries.setEnabled(true);
        jbtnShowAllEntries.setEnabled(true);
    }

    /**
     * Creates new form CalendarFrame
     */
    public CalendarFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar = new com.toedter.calendar.JCalendar();
        jbtnShowDateEntries = new javax.swing.JButton();
        jbtnConnectToDb = new javax.swing.JButton();
        jbtnShowAllEntries = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Календарь записей на прием к врачу");

        jCalendar.setDate(new java.util.Date());

        jbtnShowDateEntries.setText("Показать записи на дату");
        jbtnShowDateEntries.setEnabled(false);
        jbtnShowDateEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowDateEntriesActionPerformed(evt);
            }
        });

        jbtnConnectToDb.setText("Подключиться к базе данных");
        jbtnConnectToDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConnectToDbActionPerformed(evt);
            }
        });

        jbtnShowAllEntries.setText("Показать все записи");
        jbtnShowAllEntries.setEnabled(false);
        jbtnShowAllEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowAllEntriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnShowDateEntries)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnShowAllEntries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnConnectToDb)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnShowDateEntries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConnectToDb)
                    .addComponent(jbtnShowAllEntries))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnShowDateEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowDateEntriesActionPerformed
        presenter.showDateEntries();
    }//GEN-LAST:event_jbtnShowDateEntriesActionPerformed

    private void jbtnConnectToDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConnectToDbActionPerformed
        presenter.showConnect();
    }//GEN-LAST:event_jbtnConnectToDbActionPerformed

    private void jbtnShowAllEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowAllEntriesActionPerformed
        presenter.showAllEntries();
    }//GEN-LAST:event_jbtnShowAllEntriesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JButton jbtnConnectToDb;
    private javax.swing.JButton jbtnShowAllEntries;
    private javax.swing.JButton jbtnShowDateEntries;
    // End of variables declaration//GEN-END:variables

}
