/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.exceptions.WrongDayOfWeekException;
import com.view.interfaces.ICalendarView;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author ALEX
 */
public class CalendarFrame extends AbstractFrame implements ICalendarView{

    @Override
    public Date getCheckedDate() throws WrongDayOfWeekException{
        Date date = jCalendar.getDate();
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(date);
        int dayOfWeek = calendar.get(Calendar.DAY_OF_WEEK);
        
        switch (dayOfWeek) {
            case Calendar.MONDAY :
            case Calendar.WEDNESDAY :
            case Calendar.SATURDAY :
                return date;
                
            default : 
                throw new WrongDayOfWeekException();
        }
    }

    @Override
    public void lockEntriesView() {
        jbtnShowEntries.setEnabled(false);
    }

    @Override
    public void unlockEntriesView() {
        jbtnShowEntries.setEnabled(true);
    }
    
    /**
     * Creates new form CalendarFrame
     */
    public CalendarFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar = new com.toedter.calendar.JCalendar();
        jbtnShowEntries = new javax.swing.JButton();
        jbtnConnectToDb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Календарь записей на прием к врачу");

        jCalendar.setDate(new java.util.Date());

        jbtnShowEntries.setText("Показать записи");
        jbtnShowEntries.setEnabled(false);
        jbtnShowEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowEntriesActionPerformed(evt);
            }
        });

        jbtnConnectToDb.setText("Подключиться к базе данных");
        jbtnConnectToDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConnectToDbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnShowEntries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnConnectToDb)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnShowEntries)
                    .addComponent(jbtnConnectToDb))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnShowEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowEntriesActionPerformed
        presenter.showEntries();
    }//GEN-LAST:event_jbtnShowEntriesActionPerformed

    private void jbtnConnectToDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConnectToDbActionPerformed
        presenter.showConnect();
    }//GEN-LAST:event_jbtnConnectToDbActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JButton jbtnConnectToDb;
    private javax.swing.JButton jbtnShowEntries;
    // End of variables declaration//GEN-END:variables

}
