/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.view.interfaces.IDateEntriesView;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ListSelectionModel;

/**
 *
 * @author ALEX
 */
public class DateEntriesFrame extends AbstractEntriesFrame implements IDateEntriesView {

    @Override
    public void setCurentDate(Date date) {

        String title = "Запись пациентов на ";
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        jlblTitle.setText(title + dateFormat.format(date));
    }

    /**
     * Creates new form EntriesFrame
     */
    public DateEntriesFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setChildCloseOperation();
        tableModel.hideColumn(0);
        tableModel.hideColumn(1);
        jtblEntries.getColumnModel().getColumn(0).setCellRenderer(getCenterCellRender());
        jtblEntries.getColumnModel().getColumn(6).setCellRenderer(getCenterCellRender());
        jtblEntries.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jscrollEntries = new javax.swing.JScrollPane();
        jtblEntries = new javax.swing.JTable();
        jbtnClose = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Таблица записей на прием к врачу");
        setResizable(false);

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText(" ");

        jtblEntries.setModel(tableModel);
        jtblEntries.setFillsViewportHeight(true);
        jtblEntries.setName(""); // NOI18N
        jtblEntries.setRowHeight(20);
        jscrollEntries.setViewportView(jtblEntries);

        jbtnClose.setText("<< Вернуться к выбору даты");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jbtnDelete.setText("Удалить запись");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscrollEntries, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscrollEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnClose)
                    .addComponent(jbtnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        presenter.showCalendar();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        int rowIndex = jtblEntries.getSelectedRow();
        if (rowIndex != -1) {
            if (presenter.deleteEntry(tableModel.getId(rowIndex))) {
                presenter.showDateEntries();
            }
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JScrollPane jscrollEntries;
    private javax.swing.JTable jtblEntries;
    // End of variables declaration//GEN-END:variables
}
